# Wowchemy Website Builder
# https://wowchemy.com
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.

#baseURL = 'https://sustainable-recsts.github.io/'
#languageCode = 'en-us'
#title = 'Human-Centered and Sustainable Recommender Systems'
#theme = 'Academic'